Add chest module
MightyPirates/Scannable pull request #130
Opened 2023-08-27 17:40 UTC by curio-sitas

# Feature
This PR is about adding a new module to the scanner, the chest module. It is able to scan chests (normal and trapped ones), barrels and shulker boxes. The feature has been added (and tested) on both fabric and forge implementations.

Here are some screenshots : 
# Recipe
![2023-08-27_18 40 15](https://github.com/MightyPirates/Scannable/assets/26415466/d11dc2b0-f885-4818-981c-28e87554f81c)
# Scan 
![2023-08-27_18 55 57](https://github.com/MightyPirates/Scannable/assets/26415466/d60aa600-d81e-4421-a069-d5c4e27e0312)
![2023-08-27_18 56 18](https://github.com/MightyPirates/Scannable/assets/26415466/4ae04d6c-4085-4642-aa28-352b226445eb)
# Todo
- [ ] Translate in other language than english

2023-09-17 12:38 UTC, fnuecke requested changes
Thanks for your work on this!  Just a couple minor and one or two functional remarks.

2023-09-17 12:38 UTC, fnuecke commented on common/src/main/java/li/cil/scannable/common/config/CommonConfig.java
> +    public static Set<ResourceLocation> commonChestTags = getDefaultChestsTags();
Please stick to the order of things in this class, i.e. fields first, then methods.
So have the new fields above the `getDefaultCommonOreTags()`.

2023-09-17 12:38 UTC, fnuecke commented on common/src/main/resources/assets/scannable/lang/en_us.json
> +  "item.scannable.chest_module.desc": "Detects chests blocks (e.g. chests, barrels, shulker boxes).",
Think this should read "Detects chest blocks" (i.e. no plural on the chest), no?  That said, given the list it picks up, a better description might be "Detects storage blocks"?

2023-09-17 12:38 UTC, fnuecke commented on fabric/src/main/resources/data/scannable/recipes/chest_module.json
> +}
Please stick to formatting of other data files for consistency (using 2 space indentation, which IIRC is also what pops out when running the data generators).

2023-09-17 12:38 UTC, fnuecke commented on forge/src/main/resources/data/scannable/recipes/chest_module.json
> +        }
Please stick to consistent formatting here, too (2 space indentation).

2023-09-17 12:38 UTC, fnuecke commented on common/src/main/java/li/cil/scannable/common/scanning/ChestScannerModule.java
> +    public static void clearCache() {
I don't see this being called from the `ProviderCacheManagerImpl` classes?

2023-09-17 21:49 UTC, curio-sitas commented
Sorry for the formating mistakes, i resolved all your remarks.

2023-09-17 22:24 UTC, fnuecke commented on common/src/main/java/li/cil/scannable/common/scanning/ChestScannerModule.java
> +    public static void clearCache() {
Ah, sorry, I was not clear enough here: I did not mean to the method can be removed, but that it should be called by these classes - as is the case for the modules that cache their filters, like the common/rare ores ones.

2023-09-17 22:26 UTC, fnuecke commented
Also to make the automated checks happy, you'll need to run `./gradlew :spotlessApply` or clean up manually (see workflow output).

2023-09-18 17:52 UTC, curio-sitas commented
> Also to make the automated checks happy, you'll need to run `./gradlew :spotlessApply` or clean up manually (see workflow output).

I used the command before push the commit

2023-09-19 07:35 UTC, fnuecke commented
If I'm not mistaken the `clearCache` call is still missing from the Forge `ProviderCacheManagerImpl` (I'm only seeing it in the Fabric one)?

Once that's in I think this one's good to go :)

2023-09-19 18:10 UTC, curio-sitas commented
> If I'm not mistaken the `clearCache` call is still missing from the Forge `ProviderCacheManagerImpl` (I'm only seeing it in the Fabric one)?
> 
> Once that's in I think this one's good to go :)

Done 👍

2023-09-21 20:32 UTC, fnuecke approved these changes

2023-09-21 20:42 UTC, merged

2023-09-21 20:42 UTC, fnuecke commented
Thanks for the PR!